name: zippy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  keyboard_dismisser: ^3.0.0
  flutter_multi_formatter: ^2.13.0
  url_launcher: ^6.3.0
  mobile_scanner: ^5.2.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  bloc: ^8.1.4
  meta: ^1.15.0
  cloud_functions: ^4.7.6
  uuid: ^4.5.0
  dio: ^5.7.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/